version: "3.9"
services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    image: ig-clone-production
    ports: 
      - "8080:8080"
    networks: 
      - app-network
    env_file: .env
    environment: 
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on: 
      - "production-db"
  production-db:
    image: postgres
    ports: 
      - "5432:5432"
    networks: 
      - app-network
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
networks:
  app-network:
    driver: bridge