version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: npm run dev
    ports:
      - "8080:8080"
    environment:
      - DEV_DB_HOST=${DEV_DB_HOST}
      - DEV_DB_USER=${DEV_DB_USER}
      - DEV_DB_PASSWORD=${DEV_DB_PASSWORD}
      - DEV_DB_NAME=${DEV_DB_NAME}
    depends_on:
      - "dev-db"
      - "test-db"
  dev-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DEV_DB_USER}
      - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
      - POSTGRES_DB=${DEV_DB_NAME}
  test-db:
    image: postgres
    ports:
      - "5433:5432"
    environment: 
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
volumes:
  node_modules: