version: "3.9"
services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: demo
    image: ig-clone-demo
    ports: 
      - "8080:8080"
    command: npm run serve
    env_file: .env
    environment: 
      - NODE_ENV=demo
      - DEMO_DB_HOST=${DEMO_DB_HOST}
      - DEMO_DB_USER=${DEMO_DB_USER}
      - DEMO_DB_PASSWORD=${DEMO_DB_PASSWORD}
      - DEMO_DB_NAME=${DEMO_DB_NAME}
      - DEMO_ROOT_USER_NAME=${DEMO_ROOT_USER_NAME}
      - DEMO_ROOT_USER_PASSWORD=${DEMO_ROOT_USER_PASSWORD}
    depends_on: 
      - "demo-db"
  demo-db:
    image: postgres
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=${DEMO_DB_USER}
      - POSTGRES_PASSWORD=${DEMO_DB_PASSWORD}
      - POSTGRES_DB=${DEMO_DB_NAME}
  